cas:
  #Required properties
  server-url-prefix: https://sso.baicaowei.cn:8443/cas
  server-login-url: ${cas.server-url-prefix}/login
  client-host-url: https://oauth.demo.bcw.com:${server.port}

  #Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
  #request-wrapper-url-patterns: [/protected, /protected2]
  #assertion-thread-local-url-patterns: [/*]

  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  validation-type: CAS3

  #gateway: true
  use-session: false
  #redirect-after-validation: false
  #allowed-proxy-chains: ['https://dk.example.org:8443/proxy1', 'https://dk.example.org:8443/proxy2']
  #proxy-callback-url: https://dk.example.org:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true

casLogoutUrl: https://dk.example.org:8143/cas/logout?service=https://dk.example.org:8443

spring:
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

#Sample embedded servlet container SSL config and session tracking mode. Change as appropriate for your local deployment environment
server:
  port: 8843
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes: COOKIE
  ssl:
    enabled: true
    key-store: c://etc/cas/thekeystore
    key-store-password: changeit
  #For 'renew' param, latest Java CAS client requires that it is set as the Servlet 'context-param'. This is how to easily set it in Spring Boot
  #context-parameters.renew: true


logging.level:
    org.jasig.cas: DEBUG
